version: '2'
services:
    catalog-app:
        image: catalog
        external_links:
            - catalog-mysql:mysql
            - catalog-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/catalog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    catalog-mysql:
        extends:
            file: mysql.yml
            service: catalog-mysql
    catalog-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: catalog-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
